export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const FETCH_FOLLOWERS_PENDING = 'FETCH_FOLLOWERS_PENDING';
export const FETCH_FOLLOWERS_FULFILLED = 'FETCH_FOLLOWERS_FULFILLED';
export const FETCH_FOLLOWERS_REJECTED = 'FETCH_FOLLOWERS_REJECTED';
export const CLEAR_USER_FOLLOWERS = 'CLEAR_USER_FOLLOWERS';
